name = "checker"
version = "0.1.0"
keywords = ["math"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0"

[[lean_exe]]
name = "check"
root = "Check"
supportInterpreter = true

[[lean_exe]]
name = "check_with_answer"
root = "CheckWithAnswer"
supportInterpreter = true

[[lean_exe]]
name = "xyzzy"
root = "Xyzzy"
supportInterpreter = true
